### PR TITLE
Convert typescript Server

### PR DESCRIPTION
**Pull request by giangnt-orai**
* js server to ts server - init

* executor report: 2 api list, finished

* executor report: validate claim

* executor report: claim post

* report: list reports submitted

* report: report submit

* proof executor

* infrastructure docker

* commander: interval

* interval run get data exec wallet

* mnemonic change obj key

### CODE REVIEW

**Comment by giangnt-orai** [comment]
@ducphamle2 chú xem commit cuối trong cái pull request này nhé, a thêm data type rồi đó
https://github.com/oraichain/aioracle/pull/19/commits/71293000d45f25b5e468941fc052d57404a07d30

**Comment by giangnt-orai** [comment]
@ducphamle2 Đã thêm type cho requestData: https://github.com/oraichain/aioracle/pull/19/commits/50ea7748c2c6692e8ac63492aeaf663ac52a6c42

**Comment by giangnt-orai** [comment]
@ducphamle2 @im6h fixed "async in promise.all" comment in last commit https://github.com/oraichain/aioracle/pull/19/commits/e73de5fecdc02d4ca5e8a32bec59dba5add84284

**Review by ducphamle2 — APPROVED** [review]
lgtm

**Pull request merged**
